#!/bin/bash

datafilepath="datafile$$"

echo "Number of args: $#"

if [ "$#" = "1" ]; then
  cat > "${datafilepath}"
elif [ "$#" = "2" ]; then
  datafilepath=$2
fi

echo "Reading from ${datafilepath}..."
cat ${datafilepath}
