#!/bin/bash

sum=0
TMP1="tmp$$"
trap "rm -f ${TMP1}" INT HUP TERM
echo -e "8\n7\n6" > ${TMP1}

while read num; do
  echo 'In loop'
  echo "num: ${num}"
  sum=`expr ${sum} + ${num}`
  echo "sum: ${sum}"
  echo -e "End of loop\n"
done < ${TMP1}

rm ${TMP1}
